name: beto_common
version: 0.1.0
description: Common components for the Beto benchmarking tool.
repository: https://github.com/blaugold/beto
homepage: https://github.com/blaugold/beto/tree/main/packages/beto_common
issue_tracker: https://github.com/blaugold/beto/issues

environment:
  sdk: ^3.0.0

dependencies:
  json_annotation: ^4.9.0
  meta: ^1.8.0
  uuid: ^4.0.0

dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  test: ^1.21.6
