include: all_lint_rules.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: false
  errors:
    included_file_warning: ignore
  exclude:
    - '**/*.g.dart'

linter:
  rules:
    always_put_required_named_parameters_first: false
    always_specify_types: false
    always_use_package_imports: false
    prefer_asserts_with_message: false
    prefer_final_parameters: false
    public_member_api_docs: false
    prefer_double_quotes: false
    unnecessary_final: false
    flutter_style_todos: false
