name: beto_client
version: 0.1.0
description: Client for the Beto benchmarking tool.
repository: https://github.com/blaugold/beto
homepage: https://github.com/blaugold/beto/tree/main/packages/beto_client
issue_tracker: https://github.com/blaugold/beto/issues

environment:
  sdk: ^3.0.0

dependencies:
  beto_common: ^0.1.0+0
  http: ^1.0.0
