name: beto_client
version: 0.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  beto_common: ^0.0.0
  http: ^0.13.5
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
