name: beto_server
version: 0.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

bin:
  beto_server:

dependencies:
  beto_common: ^0.0.0
  googleapis: ^9.2.0
  googleapis_auth: ^1.3.1
  http: ^0.13.5
  shelf: ^1.4.0
  shelf_router: ^1.1.3

dev_dependencies:
  test: ^1.21.6
