name: beto_server
version: 0.1.0+1
description: Server for the Beto benchmarking tool.
repository: https://github.com/blaugold/beto
homepage: https://github.com/blaugold/beto/tree/main/packages/beto_server
issue_tracker: https://github.com/blaugold/beto/issues

environment:
  sdk: ^3.0.0

bin:
  beto_server:

dependencies:
  args: ^2.3.1
  beto_common: ^0.1.0+0
  googleapis: ^13.0.0
  googleapis_auth: ^1.6.0
  http: ^1.0.0
  logging: ^1.1.0
  meta: ^1.8.0
  recase: ^4.1.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  uuid: ^4.0.0

dev_dependencies:
  beto_client: ^0.1.0
  test: ^1.21.6
