name: beto_server
version: 0.1.0
description: Server for the Beto benchmarking tool.
repository: https://github.com/blaugold/beto
homepage: https://github.com/blaugold/beto/tree/main/packages/beto_server
issue_tracker: https://github.com/blaugold/beto/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

bin:
  beto_server:

dependencies:
  args: ^2.3.1
  beto_common: ^0.1.0
  googleapis: ^9.2.0
  googleapis_auth: ^1.3.1
  http: ^0.13.5
  logging: ^1.1.0
  meta: ^1.8.0
  recase: ^4.1.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  uuid: ^3.0.6

dev_dependencies:
  beto_client: ^0.1.0
  test: ^1.21.6
