name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, dev]
    continue-on-error: ${{ matrix.sdk == 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install Melos
        run: dart pub global activate melos
      - name: Bootstrap
        run: melos bootstrap
      - name: Check code generation
        run: melos code-gen:check --no-select
      - name: Check formatting
        run: melos format:check --no-select
      - name: Analyze
        run: melos analyze --no-select

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        sdk: [stable, dev]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Google Cloud Service Account
        env:
          GOOGLE_CLOUD_SERVICE_ACCOUNT:
            ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}
        run:
          echo "$GOOGLE_CLOUD_SERVICE_ACCOUNT" >
          packages/beto_server/test-service-account.json
        shell: bash
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install Melos
        run: dart pub global activate melos
      - name: Bootstrap
        run: melos bootstrap
      - name: Test
        run: melos test --no-select
